name: gym_hub
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For creating beautiful charts and graphs
  fl_chart: ^0.68.0
  
  # For parsing CSV data
  csv: ^5.0.1
  
  # For state management and dependency injection
  flutter_riverpod: ^2.3.6
  
  # For formatting dates
  intl: ^0.18.1
  
  # For responsive layouts
  responsive_builder: ^0.7.0

  # For sharing content
  share_plus: ^7.2.2
  
  # For Lottie animations
  lottie: ^3.1.0
  
  # For slidable list items
  flutter_slidable: ^3.1.0
  
  # For vector icons
  flutter_vector_icons: ^2.0.0

  # For custom fonts
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
#    - assets/animations/
